---
abstract: 'Parse metadata files from your Humax satellite TV receiver.'
author:
  - "spudsoup\" <\"spudsoup@cpan.org"
build_requires:
  DateTime: 0
  Moose: 0
  Moose::Util::TypeConstraints: 0
  Test::CheckManifest: 0.9
  Test::More: 0
  Test::Most: 0
  Test::Pod: 1.41
  Test::Pod::Coverage: 1.08
  Trait::Attribute::Derived: 0
  namespace::autoclean: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.008, CPAN::Meta::Converter version 2.133380'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: TV-Humax-Foxsat
version: 0.04
